In [3]:
import numpy as np

In [4]:
def gauss_elimination(A, b):
    """
    Solve Ax = b using Gaussian Elimination.
    A: coefficient matrix (n x n)
    b: right-hand side vector (n x 1)
    Returns: solution vector x
    """
    n = len(b)
    # Augmented matrix
    M = np.hstack([A.astype(float), b.reshape(-1,1).astype(float)])
    
    # Forward elimination
    for i in range(n):
        # Pivoting (swap rows if needed)
        max_row = i + np.argmax(abs(M[i:, i]))
        if max_row != i:
            M[[i, max_row]] = M[[max_row, i]]
        
        # Make pivot = 1
        pivot = M[i, i]
        M[i] = M[i] / pivot
        
        # Eliminate below
        for j in range(i+1, n):
            M[j] = M[j] - M[j, i] * M[i]
    
    # Back substitution
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = M[i, -1] - np.dot(M[i, i+1:n], x[i+1:n])
    
    return x

In [6]:
# Example usage:
A = np.array([[2, -1, 1],
              [3, 3, 9],
              [3, 3, 5]], dtype=float)

b = np.array([2, -1, 4], dtype=float)
M = np.hstack([A.astype(float), b.reshape(-1,1).astype(float)])
print(M)
# solution = gauss_elimination(A, b)
# print("Solution:", solution)

[[ 2. -1.  1.  2.]
 [ 3.  3.  9. -1.]
 [ 3.  3.  5.  4.]]
